import { auth, db, onAuthStateChanged, signOut, collection, doc, addDoc, setDoc, getDoc, getDocs, updateDoc, deleteDoc, query, where, orderBy, serverTimestamp, onSnapshot, limit } from "./firebase.js";
import { setupDashboardTabs, safeText, statusClass, statusLabel, money, whatsappUrl, directionsUrl, wazeUrl, mapsUrl, formatDate, showMessage, requestLocationPermission, MANAGER_PHONE, $ } from "./ui.js";

setupDashboardTabs("perfil");
$("logoutBtn")?.addEventListener("click", logout); $("logoutMobileBtn")?.addEventListener("click", logout);
async function logout(){ await signOut(auth); location.href="login.html"; }
let userId, profile={}, vehicles=[], freights=[], applications=[], reviews=[], watchId=null;

onAuthStateChanged(auth, async user=>{
  if(!user) return location.href="login.html";
  userId=user.uid; const snap=await getDoc(doc(db,"usuarios",user.uid)); profile=snap.data()||{};
  if((profile.tipo||profile.role)!=="caminhoneiro") return location.href="login.html";
  $("welcomeTitle").textContent=`Olá, ${profile.nome||profile.name||"caminhoneiro"}`;
  $("availability").value=profile.disponibilidade||"disponivel"; $("preferredRoutes").value=profile.preferredRoutes||""; $("cargoPreferences").value=profile.cargoPreferences||"";
  requestLocationPermission(null, (text,type)=>showMessage($("profileMessage"), text, type));
  listen();
});
function listen(){
  onSnapshot(query(collection(db,"caminhoneiros",userId,"veiculos"), orderBy("createdAt","desc"), limit(50)), s=>{ vehicles=s.docs.map(d=>({id:d.id,...d.data()})); renderVehicles(); updateCounts(); }, e=>showMessage($("vehicleMessage"),"Nao foi possivel carregar seus veiculos agora. Tente atualizar a pagina.","error"));
  onSnapshot(query(collection(db,"fretes"), where("status","==","aberto"), limit(80)), s=>{ freights=s.docs.map(d=>({id:d.id,...d.data()})); renderAvailableFreights(); updateCounts(); }, console.error);
  onSnapshot(query(collection(db,"caminhoneiros",userId,"minhasCandidaturas"), orderBy("updatedAt","desc"), limit(80)), s=>{ applications=s.docs.map(d=>({id:d.id,...d.data()})); renderApplications(); updateCounts(); }, e=>showMessage($("profileMessage"),"Nao foi possivel carregar suas candidaturas agora. Tente atualizar a pagina.","error"));
  onSnapshot(query(collection(db,"avaliacoes"), where("driverId","==",userId), limit(30)), s=>{ reviews=s.docs.map(d=>({id:d.id,...d.data()})); renderMyReviews(); }, console.error);
}
function updateCounts(){ $("myVehiclesCount").textContent=vehicles.length; $("availableFreightsCount").textContent=freights.length; $("myApplicationsCount").textContent=applications.length; }
$("availabilityForm")?.addEventListener("submit", async e=>{ e.preventDefault(); const payload={disponibilidade:$("availability").value, availableFrom:$("availableFrom").value, preferredRoutes:$("preferredRoutes").value.trim(), cargoPreferences:$("cargoPreferences").value.trim(), updatedAt:serverTimestamp()}; await setDoc(doc(db,"caminhoneiros",userId),payload,{merge:true}); await setDoc(doc(db,"usuarios",userId),payload,{merge:true}); showMessage($("profileMessage"),"Disponibilidade atualizada."); });

$("vehicleForm")?.addEventListener("submit", async e=>{ e.preventDefault(); const payload={ plate:$("plate").value.trim().toUpperCase(), model:$("model").value.trim(), year:Number($("year").value), type:$("type").value, capacity:Number($("capacity").value), status:$("vehicleStatus").value, updatedAt:serverTimestamp() }; const id=$("vehicleId").value; if(id){ await updateDoc(doc(db,"caminhoneiros",userId,"veiculos",id),payload); showMessage($("vehicleMessage"),"Veículo atualizado."); } else { await addDoc(collection(db,"caminhoneiros",userId,"veiculos"),{...payload, createdAt:serverTimestamp()}); showMessage($("vehicleMessage"),"Veículo cadastrado."); } clearVehicleForm(); });
$("clearVehicleForm")?.addEventListener("click", clearVehicleForm);
function clearVehicleForm(){ $("vehicleForm")?.reset(); $("vehicleId").value=""; }
function renderVehicles(){ const el=$("vehiclesList"); if(!el)return; el.innerHTML=vehicles.map(v=>`<article class="item"><div class="item-header"><div><h3>${safeText(v.type)} ${safeText(v.model)}</h3><p>Placa ${safeText(v.plate)} • Ano ${safeText(v.year)} • ${safeText(v.capacity)} kg • ${safeText(statusLabel(v.status))}</p></div><span class="badge ${v.status==='ativo'?'open':'pending'}">${safeText(v.status)}</span></div><div class="actions"><button onclick="editarVeiculo('${v.id}')">Editar</button><button class="danger" onclick="excluirVeiculo('${v.id}')">Excluir</button></div></article>`).join("")||`<p class="empty">Cadastre seu primeiro veículo.</p>`; }
window.editarVeiculo=id=>{ const v=vehicles.find(x=>x.id===id); if(!v)return; $("vehicleId").value=id; $("plate").value=v.plate||""; $("model").value=v.model||""; $("year").value=v.year||""; $("type").value=v.type||""; $("capacity").value=v.capacity||""; $("vehicleStatus").value=v.status||"ativo"; location.hash="#veiculos"; };
window.excluirVeiculo=async id=>{ if(confirm("Excluir este veículo?")){ await deleteDoc(doc(db,"caminhoneiros",userId,"veiculos",id)); showMessage($("vehicleMessage"),"Veículo excluído."); } };

["freightSearch","freightTypeFilter"].forEach(id=>$(id)?.addEventListener("input",renderAvailableFreights));
function renderAvailableFreights(){ const q=($("freightSearch")?.value||"").toLowerCase(), type=$("freightTypeFilter")?.value||"todos"; const applied=new Set(applications.map(a=>a.freightId||a.id)); const list=freights.filter(f=>!applied.has(f.id)&&(type==="todos"||f.vehicleType===type)&&`${f.code} ${f.originText} ${f.destinationText} ${f.cargoType}`.toLowerCase().includes(q)); const el=$("availableFreightsList"); if(!el)return; el.innerHTML=list.map(f=>`<article class="item"><div class="item-header"><div><h3>${safeText(f.code)} • ${safeText(f.originText)} → ${safeText(f.destinationText)}</h3><p>${safeText(f.cargoType)} • ${safeText(f.vehicleType)} • ${safeText(f.weight)} kg • ${money(f.price)} • ${safeText(f.deadline)}</p></div><span class="badge open">Disponível</span></div><p>${safeText(f.description,"Frete disponível para candidatura.")}</p><div class="actions"><a class="button-link" target="_blank" href="${whatsappUrl(MANAGER_PHONE,`Olá, tenho interesse no frete ${f.code}.`)}">Chamar gestor</a><button onclick="candidatar('${f.id}')">Candidatar-se</button></div></article>`).join("")||`<p class="empty">Nenhum frete disponível com estes filtros.</p>`; }
window.candidatar=async freightId=>{ if(!vehicles.length) return alert("Cadastre um veículo antes de se candidatar."); const f=freights.find(x=>x.id===freightId); const v=vehicles.find(x=>x.status==="ativo")||vehicles[0]; const proposed=prompt(`Valor proposto para o frete ${f.code}:`, f.price||""); const payload={freightId, code:f.code, driverId:userId, driverName:profile.nome||profile.name, driverPhone:profile.telefone||profile.phone, vehicleId:v.id, vehicleLabel:`${v.type} ${v.model} • ${v.plate}`, proposedValue:Number(proposed||f.price||0), status:"pendente", createdAt:serverTimestamp(), updatedAt:serverTimestamp(), originText:f.originText, destinationText:f.destinationText, cargoType:f.cargoType, price:f.price, vehicleType:f.vehicleType, deadline:f.deadline}; await setDoc(doc(db,"fretes",freightId,"candidaturas",userId),payload); await setDoc(doc(db,"caminhoneiros",userId,"minhasCandidaturas",freightId),payload,{merge:true}); await addDoc(collection(db,"fretes",freightId,"eventos"),{title:"Candidatura recebida",detail:`${payload.driverName} se candidatou ao frete.`,createdAt:serverTimestamp(),createdBy:userId}); alert("Candidatura enviada."); };

$("applicationStatusFilter")?.addEventListener("input",renderApplications);
function renderApplications(){ const st=$("applicationStatusFilter")?.value||"todos"; const list=applications.filter(a=>st==="todos"||a.status===st||a.freightStatus===st); const el=$("myApplicationsList"); if(!el)return; el.innerHTML=list.map(a=>renderApplication(a)).join("")||`<p class="empty">Você ainda não possui candidaturas.</p>`; }
function renderApplication(a){ const released=["liberado","em_andamento","indo_coleta","chegou_coleta","carregado","em_viagem","chegou_destino"].includes(a.status)||a.freightStatus==="em_andamento"; const destination=a.pickupAddress||a.originText; return `<article class="item"><div class="item-header"><div><h3>${safeText(a.code)} • ${safeText(a.originText)} → ${safeText(a.destinationText)}</h3><p>${safeText(a.cargoType)} • ${money(a.price)} • ${safeText(a.vehicleLabel)}</p></div><span class="badge ${statusClass(a.status)}">${statusLabel(a.status)}</span></div>${released?`<div class="private-box"><strong>Dados liberados da coleta</strong><p>${safeText(a.pickupAddress)} • ${safeText(a.pickupContactName)} • ${safeText(a.pickupContactPhone)}</p><p>Código da operação: <strong>${safeText(a.operationCode||a.code)}</strong></p></div><div class="actions"><a class="button-link" target="_blank" href="${directionsUrl(destination)}">Google Maps</a><a class="button-link" target="_blank" href="${wazeUrl(destination)}">Waze</a><a class="button-link" target="_blank" href="${whatsappUrl(a.managerPhone||MANAGER_PHONE,`Olá, sou o caminhoneiro do frete ${a.code}.`)}">Chamar gestor</a><button onclick="startTracking('${a.freightId||a.id}')">Enviar localização</button><button onclick="stopTracking('${a.freightId||a.id}')">Parar rastreamento</button></div><div class="quick-actions"><button onclick="updateFreightStep('${a.freightId||a.id}','indo_coleta','Estou indo para a carga')">Indo para carga</button><button onclick="updateFreightStep('${a.freightId||a.id}','chegou_coleta','Cheguei no carregamento')">Cheguei</button><button onclick="updateFreightStep('${a.freightId||a.id}','carregado','Carga coletada')">Carregado</button><button onclick="updateFreightStep('${a.freightId||a.id}','em_viagem','Em viagem')">Em viagem</button><button onclick="updateFreightStep('${a.freightId||a.id}','chegou_destino','Cheguei no destino')">No destino</button><button class="success" onclick="updateFreightStep('${a.freightId||a.id}','finalizado','Entregue')">Entregue</button></div>`:`<p class="hint">Endereço e contato serão exibidos após liberação do gestor.</p>`}</article>`; }
window.updateFreightStep=async(fid,status,label)=>{ await setDoc(doc(db,"caminhoneiros",userId,"minhasCandidaturas",fid),{status,freightStatus:status,updatedAt:serverTimestamp()},{merge:true}); await updateDoc(doc(db,"fretes",fid,"candidaturas",userId),{status,freightStatus:status,updatedAt:serverTimestamp()}).catch(()=>{}); await updateDoc(doc(db,"fretes",fid),{status: status==="finalizado"?"finalizado":"em_andamento", lastStep:label, updatedAt:serverTimestamp()}).catch(()=>{}); await addDoc(collection(db,"fretes",fid,"eventos"),{title:label, detail:`${profile.nome||profile.name} atualizou o frete.`, createdAt:serverTimestamp(), createdBy:userId}); if(status==="chegou_coleta"||status==="chegou_destino") requestLocationPermission(pos=>saveTrack(fid,pos,true), text=>alert(text)); };
window.startTracking=fid=>{ if(!navigator.geolocation) return alert("Navegador sem localização automática."); if(watchId) navigator.geolocation.clearWatch(watchId); watchId=navigator.geolocation.watchPosition(pos=>saveTrack(fid,pos,true), err=>alert(err.code===1?"Localização bloqueada. Libere a permissão no navegador para rastreamento em tempo real.":"Não foi possível obter a localização."), {enableHighAccuracy:true, maximumAge:10000, timeout:15000}); alert("Rastreamento iniciado. Mantenha esta página aberta durante o deslocamento."); };
window.stopTracking=async fid=>{ if(watchId) navigator.geolocation.clearWatch(watchId); watchId=null; await setDoc(doc(db,"fretes",fid,"rastreamento",userId),{active:false,updatedAt:serverTimestamp()},{merge:true}); alert("Rastreamento pausado."); };
async function saveTrack(fid,pos,active){ const a=applications.find(x=>(x.freightId||x.id)===fid)||{}; await setDoc(doc(db,"fretes",fid,"rastreamento",userId),{freightId:fid, code:a.code, driverId:userId, driverName:profile.nome||profile.name, lat:pos.coords.latitude, lng:pos.coords.longitude, accuracy:pos.coords.accuracy, active, originText:a.originText, destinationText:a.destinationText, updatedAt:serverTimestamp()},{merge:true}); }

$("reviewForm")?.addEventListener("submit", async e=>{ e.preventDefault(); await addDoc(collection(db,"avaliacoes"),{driverId:userId, driverName:profile.nome||profile.name, nota:Number($("reviewRating").value), texto:$("reviewText").value.trim(), publico:$("reviewPublic").value==="true", createdAt:serverTimestamp()}); e.target.reset(); showMessage($("reviewMessage"),"Avaliação enviada."); });
function renderMyReviews(){ const el=$("myReviewsList"); if(!el)return; el.innerHTML=reviews.map(r=>`<article class="item"><strong>${"★".repeat(Number(r.nota||0))}</strong><p>${safeText(r.texto)}</p><small>${formatDate(r.createdAt)}</small></article>`).join("")||`<p class="empty">Nenhuma avaliação enviada.</p>`; }
