import { auth, db, onAuthStateChanged, signOut, collection, doc, addDoc, setDoc, getDoc, getDocs, updateDoc, query, where, orderBy, serverTimestamp, onSnapshot, limit } from "./firebase.js";
import { configurarSelectEstadoCidade, obterLocalidade } from "./ibge.js";
import { abrirWhatsAppRegistrando } from "./comercial.js";
import { setupDashboardTabs, safeText, statusClass, statusLabel, money, whatsappUrl, buildFreightCode, formatDate, showMessage, requestLocationPermission, MANAGER_PHONE, $ } from "./ui.js";

setupDashboardTabs("dashboard");
configurarSelectEstadoCidade({ estadoId:"originState", cidadeId:"originCity", estadoPlaceholder:"Estado origem", cidadePlaceholder:"Cidade origem" });
configurarSelectEstadoCidade({ estadoId:"destinationState", cidadeId:"destinationCity", estadoPlaceholder:"Estado destino", cidadePlaceholder:"Cidade destino" });
$("logoutBtn")?.addEventListener("click", logout); $("logoutMobileBtn")?.addEventListener("click", logout);
async function logout(){ await signOut(auth); location.href="login.html"; }
let uid, profile={}, freights=[], commissions=[];
onAuthStateChanged(auth, async user=>{ if(!user)return location.href="login.html"; uid=user.uid; profile=(await getDoc(doc(db,"usuarios",uid))).data()||{}; if((profile.tipo||profile.role)!=="empresa") return location.href="login.html"; $("companyTitle").textContent=profile.empresaNome||profile.nome||"Painel da empresa"; requestLocationPermission(null,()=>{}); listen(); });
function listen(){ onSnapshot(query(collection(db,"fretes"), where("empresaId","==",uid), orderBy("createdAt","desc"), limit(80)), async s=>{ freights=s.docs.map(d=>({id:d.id,...d.data()})); await attachApps(); renderFreights(); updateCards(); }, console.error); onSnapshot(query(collection(db,"comissoes"), where("empresaId","==",uid), limit(80)), s=>{ commissions=s.docs.map(d=>({id:d.id,...d.data()})); renderCommissions(); updateCards(); }, console.error); }
async function attachApps(){ await Promise.all(freights.map(async f=>{ try{ const s=await getDocs(query(collection(db,"fretes",f.id,"candidaturas"),limit(30))); f.applications=s.docs.map(d=>({id:d.id,...d.data()})); }catch{ f.applications=[]; } })); }
function updateCards(){ $("companyActiveFreights").textContent=freights.filter(f=>f.status!=="finalizado"&&f.status!=="cancelado").length; $("companyApplications").textContent=freights.reduce((s,f)=>s+(f.applications?.length||0),0); $("companyCommissions").textContent=money(commissions.filter(c=>c.status!=="paga").reduce((s,c)=>s+Number(c.valorComissao||0),0)); }
$("companyFreightForm")?.addEventListener("submit", async e=>{ e.preventDefault(); const origin=obterLocalidade("originState","originCity"), dest=obterLocalidade("destinationState","destinationCity"); const price=Number($("price").value||0); const code=buildFreightCode(); const freight={ code, empresaId:uid, empresaNome:profile.empresaNome||profile.nome, originText:origin.texto, destinationText:dest.texto, originUf:origin.uf, destinationUf:dest.uf, cargoType:$("cargoType").value.trim(), weight:Number($("weight").value||0), price, vehicleType:$("vehicleType").value, deadline:$("deadline").value, description:$("description").value.trim(), managerPhone:MANAGER_PHONE, status:"aberto", commissionType:"percentual", commissionValue:5, commissionAmount:price*0.05, createdBy:uid, createdAt:serverTimestamp(), updatedAt:serverTimestamp() }; const ref=await addDoc(collection(db,"fretes"),freight); await setDoc(doc(db,"fretes",ref.id,"privado","detalhes"),{pickupAddress:$("pickupAddress").value.trim(),deliveryAddress:$("deliveryAddress").value.trim(),pickupContactName:$("pickupContactName").value.trim(),pickupContactPhone:$("pickupContactPhone").value.trim(),managerPhone:MANAGER_PHONE,createdAt:serverTimestamp()}); await addDoc(collection(db,"fretes",ref.id,"eventos"),{title:"Frete criado",detail:`Empresa ${freight.empresaNome} publicou o frete ${code}.`,createdAt:serverTimestamp(),createdBy:uid}); e.target.reset(); showMessage($("formMessage"),`Frete ${code} publicado.`); });
["freightSearch","statusFilter"].forEach(id=>$(id)?.addEventListener("input",renderFreights));
function renderFreights(){ const q=($("freightSearch")?.value||"").toLowerCase(), st=$("statusFilter")?.value||"todos"; const list=freights.filter(f=>(st==="todos"||f.status===st)&&`${f.code} ${f.originText} ${f.destinationText} ${f.cargoType}`.toLowerCase().includes(q)); const el=$("freightsList"); if(!el)return; el.innerHTML=list.map(f=>`<article class="item"><div class="item-header"><div><h3>${safeText(f.code)} • ${safeText(f.originText)} → ${safeText(f.destinationText)}</h3><p>${safeText(f.cargoType)} • ${money(f.price)} • ${statusLabel(f.status)}</p></div><span class="badge ${statusClass(f.status)}">${statusLabel(f.status)}</span></div><div class="actions"><a class="button-link" href="acompanhar.html?codigo=${encodeURIComponent(f.code)}" target="_blank">Acompanhar</a><a class="button-link" href="${whatsappUrl(MANAGER_PHONE,`Olá, sou da empresa ${profile.empresaNome||profile.nome}. Quero falar sobre o frete ${f.code}.`)}" target="_blank">Chamar gestor</a><button onclick="confirmarContratacao('${f.id}')">Confirmar contratação</button><button onclick="confirmarEntrega('${f.id}')">Confirmar entrega</button><a class="button-link" href="validar.html?codigo=${encodeURIComponent(f.code)}" target="_blank">Validar código</a></div><div class="applications-box"><strong>Candidaturas</strong>${(f.applications||[]).map(a=>`<div class="application-row"><div><strong>${safeText(a.driverName)}</strong><p>${safeText(a.driverPhone)} • ${safeText(a.vehicleLabel)} • ${money(a.proposedValue||f.price)}</p></div><span class="badge ${statusClass(a.status)}">${statusLabel(a.status)}</span><a class="button-link" target="_blank" href="${whatsappUrl(a.driverPhone,`Olá, sou da empresa responsável pelo frete ${f.code}.`)}">WhatsApp</a></div>`).join("")||"<p class='muted'>Sem candidaturas.</p>"}</div></article>`).join("")||`<p class="empty">Nenhum frete encontrado.</p>`; }
window.confirmarContratacao=async id=>{ const f=freights.find(x=>x.id===id); if(!f)return; await updateDoc(doc(db,"fretes",id),{contratacaoConfirmada:true,status:"em_andamento",updatedAt:serverTimestamp()}); await setDoc(doc(db,"comissoes",id),{freightId:id, code:f.code, empresaId:uid, empresaNome:profile.empresaNome||profile.nome, empresaTelefone:profile.telefone, driverId:f.selectedDriverId||"", driverName:f.selectedDriverName||"", valorFrete:Number(f.price||0), valorComissao:Number(f.commissionAmount||Number(f.price||0)*0.05), status:"pendente", createdAt:serverTimestamp(), updatedAt:serverTimestamp()},{merge:true}); await addDoc(collection(db,"fretes",id,"eventos"),{title:"Contratacao confirmada",detail:"A empresa confirmou a contratacao pela plataforma.",createdAt:serverTimestamp(),createdBy:uid}); alert("Contratacao confirmada e comissao registrada."); };
window.confirmarEntrega=async id=>{ await updateDoc(doc(db,"fretes",id),{status:"finalizado",confirmedByCompany:true,updatedAt:serverTimestamp()}); await addDoc(collection(db,"fretes",id,"eventos"),{title:"Entrega confirmada",detail:"A empresa confirmou a conclusão da operação.",createdAt:serverTimestamp(),createdBy:uid}); };
function renderCommissions(){ const el=$("commissionsList"); if(!el)return; el.innerHTML=commissions.map(c=>`<article class="item"><div class="item-header"><div><h3>${safeText(c.code)}</h3><p>Caminhoneiro ${safeText(c.driverName)} • Comissão ${money(c.valorComissao)} • Criada em ${formatDate(c.createdAt)}</p></div><span class="badge ${statusClass(c.status)}">${statusLabel(c.status)}</span></div></article>`).join("")||`<p class="empty">Nenhuma comissão registrada.</p>`; }

setTimeout(()=>{ const el=$("companyReferralLink"); if(el) el.textContent=location.origin+location.pathname.replace(/empresa\.html$/,"")+"cadastro-empresa.html?ref="+uid; }, 800);
window.chamarGestorEmpresa=(code)=>abrirWhatsAppRegistrando(MANAGER_PHONE,`Ola, sou da empresa ${profile.empresaNome||profile.nome}. Quero falar sobre o frete ${code}.`,{codigo:code,origem:"empresa"});
