import { auth, db, onAuthStateChanged, collection, doc, getDoc, updateDoc, query, where, orderBy, onSnapshot, limit } from "./firebase.js";
import { $, safeText, formatDate, statusLabel, statusClass, money } from "./ui.js";
let uid=null,profile={},freights=[],notifications=[];
onAuthStateChanged(auth,async user=>{if(!user)return;uid=user.uid;profile=(await getDoc(doc(db,"usuarios",uid))).data()||{};if(!["empresa","empresa_admin","empresa_operacional"].includes(profile.tipo||profile.role))return;listenExtra();});
function listenExtra(){onSnapshot(query(collection(db,"fretes"),where("empresaId","==",uid),orderBy("createdAt","desc"),limit(80)),s=>{freights=s.docs.map(d=>({id:d.id,...d.data()}));renderOnboarding();renderAgenda();},console.warn);onSnapshot(query(collection(db,"notificacoes"),where("empresaId","==",uid),orderBy("createdAt","desc"),limit(50)),s=>{notifications=s.docs.map(d=>({id:d.id,...d.data()}));renderNotifications();},console.warn);}
function completeness(){const items=[["Perfil da empresa",!!(profile.empresaNome||profile.nome)&&!!profile.telefone],["Aceite comercial",!!profile.aceiteComissao],["Primeira carga publicada",freights.length>0],["Contato operacional",!!profile.telefone],["Cidade base",!!(profile.baseLocation||profile.cidade)]];const pct=Math.round(items.filter(x=>x[1]).length/items.length*100);return{items,pct};}
function renderOnboarding(){const el=$("companyOnboarding");if(!el)return;const c=completeness();el.innerHTML=`<article class="onboarding-card"><h3>Perfil ${c.pct}% completo</h3><div class="onboarding-progress"><span style="width:${c.pct}%"></span></div><p class="hint">Complete os dados para agilizar aprovações e comunicação.</p></article><article class="checklist-card"><h3>Checklist</h3>${c.items.map(i=>`<div class="checklist-row"><span>${i[0]}</span><strong class="${i[1]?'checklist-ok':'checklist-warn'}">${i[1]?'OK':'Pendente'}</strong></div>`).join('')}</article><article class="action-card"><h3>Próxima ação</h3><p>${c.pct<100?'Complete os itens pendentes para operar com mais confiança.':'Seu cadastro está pronto para operar.'}</p><a class="button-link" href="#novo-frete">Publicar carga</a></article>`;}
function renderAgenda(){const el=$("companyAgendaList");if(!el)return;const today=new Date().toISOString().slice(0,10);const list=freights.filter(f=>f.deadline>=today&&!['finalizado','cancelado'].includes(f.status)).slice(0,30);el.innerHTML=list.map(f=>`<article class="item"><div class="item-header"><div><h3>${safeText(f.code)} • ${safeText(f.originText)} → ${safeText(f.destinationText)}</h3><p>Coleta/entrega prevista: ${safeText(f.deadline)} • Valor ${money(f.price)}</p></div><span class="badge ${statusClass(f.status)}">${statusLabel(f.status)}</span></div></article>`).join('')||`<p class="empty">Nenhuma carga agendada.</p>`;}
function renderNotifications(){const unread=notifications.filter(n=>!n.lidaEmpresa).length;if($("companyUnreadDot")){ $("companyUnreadDot").style.display=unread?'inline-grid':'none';$("companyUnreadDot").textContent=unread;}const el=$("companyNotificationsList");if(!el)return;el.innerHTML=notifications.map(n=>`<article class="notification-card"><div class="item-header"><div><h3>${safeText(n.titulo||'Atualização')}</h3><p>${safeText(n.texto||'')}</p><small>${formatDate(n.createdAt)}</small></div><span class="badge ${n.lidaEmpresa?'done':'pending'}">${n.lidaEmpresa?'Lida':'Nova'}</span></div></article>`).join('')||`<p class="empty">Nenhuma notificação.</p>`;}
$("companyMarkNotificationsRead")?.addEventListener("click",async()=>{await Promise.all(notifications.filter(n=>!n.lidaEmpresa).map(n=>updateDoc(doc(db,"notificacoes",n.id),{lidaEmpresa:true})));});
